apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: kong
data:
  nginx.conf: |
    worker_processes 1;
    events {
        worker_connections 1024;
    }
    http {
        upstream kong_gateway_proxy {
                server kong-proxy.kong.svc.cluster.local:80;
        }
        server {
                listen 80 default;
                server_name _;
                client_max_body_size 0;
                location / {
                    proxy_pass http://kong_gateway_proxy;
                    proxy_set_header Host $host;  
                    proxy_set_header x-nginx-hostname $hostname;  

                    proxy_connect_timeout      2m;
                    proxy_send_timeout         2m;
                    proxy_read_timeout         2m;
                    send_timeout               2m;
                }
        }
    }