kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: "/var/lib/kubernetes/${ROOT_CA_FILE}"
authorization:
  mode: Webhook
clusterDomain: "${CLUSTER_DOMAIN}"
clusterDNS:
  - "${CLUSTER_DNS_IP_FOR_POD}"
podCIDR: "${POD_CIDR_FOR_WORKER}"
resolvConf: "/run/systemd/resolve/resolv.conf"
runtimeRequestTimeout: "15m"
tlsCertFile: "${TLS_CERT_FILE}"
tlsPrivateKeyFile: "${TLS_PRIVATE_KEY_FILE}"